server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mc_fsp?serverTimezone=UTC
    username: "n7k+nOPTf4MITQNbEcev99EWkfvCwmIDV+27IKLglJJiFVreoAvovGLY4NEQk9k2is7YDgqr3Ow+aSHULgdO4pAoIPXNym/ZV3XIKi+giQ8bOb4znDzE/BW4wlRvQKDTMNZXRAGnM4f/gg7Tj88qIAQZb9PvDW2ZQdn4QrH5Ncx0OT/3ovNhk3Hefzd6LcneBEt5SEMae2KpdFR+2IRs0AH19ZfSiLHzL0s4W2/W7XJj58DLPFPLsXUkRvf8TBimue3rDLrWKV7KWkmFZ8V9AoVjRDklZUOjM2MnoOcVHVyjaVgcEIdjHNN5qqea7tsJ+9nbmjvh9uK6JBoblu8e0w=="
    password: "YdB0WCnsnyohRgptLfflw5AA9RQFnC23j20yVyGlnh+xPuKERo1n4BKAQCbqzO085y6qHkfCqCQhbOIE4DbENq2pgbhOIGf235ZOIAReUCz+U+yU793gkg4veWBtsYJh0JhzXPnO5oKxR9eDwBCvgCWZEpF3+T8RqhC3mhI1l347Mh/eGl88iVIpKduILzik2lkWr9YC5BGoumfwrXt5aPD6DgNxFnQzGbrsvO9w3f6sRwHpx349PkL1xYcCUwhuKVThIkz5LFlmC/4jr7fay68OxDS8iQFa/hSeimkn5jkUWM4B4P1NqqgDXbIpinVG/Yh4JLZ+M8Z6i4uNmQ7cyg=="

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.mc.fsp.entity

cryptic:
  mysql:
    private-key-location: "private.key"